### ISSUE TITLE
Last Update: 1 day ago

### ISSUE THREAD

**Issue by dhezghia** [Trinovantes/WoWPay2Win#21]
BoEs would update hourly with prices/servers & now it's been 24 hours without an update.  Any idea what caused this?

**Comment by Trinovantes** [comment]
Seems Blizzard blanket banned clients from cloud IP addresses from accessing the API:

https://us.forums.blizzard.com/en/blizzard/t/oauthbattlenet-403/49393

Not much I can do besides watching the forums for updates

**Comment by dhezghia** [comment]
A new IP might resolve the issue

**Comment by Trinovantes** [comment]
Some obscure web hosts might not have their ASN banned but I'm not interested in spending $5-10 on every web host until I find one that works. Not to mention there's no guarantee they won't ban more in the future.

Since it's the weekend, we probably won't hear from their engineers until next week. If this is an intentional firewall change on Blizzard's end, then I'm going to shut down this site.

**Comment by Trinovantes** [comment]
Yea Azure IPs are also banned

https://github.com/Trinovantes/WoWPay2Win/actions/runs/7857940394/job/21442366601

Since I can't even run my CI workflow, I'm not interested in keeping the site alive if this is an intentional firewall

**Comment by cohenaj194** [comment]
I similar oauth commands from digital ocean and I have not experienced any recent 403 errors yet.  You might want to consider that if you are open to new cloud providers.

**Comment by Trinovantes** [comment]
Resolved the issue for now by proxying requests with cf workers. It may break again in the future if Blizzard updates their firewall rules

You may need to clear browser cache to see new updates
